using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        [SerializeField] public LifeCount lifecount;
        [SerializeField] public HealthBar healthbar;
    }
}
